export const SUPERVIEW_YOUTUBE_SUBSCRIPTIONS = 'SUPERVIEW_YOUTUBE_SUBSCRIPTIONS'

export const SET_CHANNEL_IDS  = 'SET_CHANNEL_IDS'
export const SET_CHANNELS     = 'SET_CHANNELS'
export const ADD_CHANNEL_ID   = 'ADD_CHANNEL_ID'
export const ADD_CHANNEL      = 'ADD_CHANNEL'
export const RESET_CHANNELS   = 'RESET_CHANNELS'
export const SET_CHAT_CHANNEL = 'SET_CHAT_CHANNEL'

export const TWITCH_AUTH_STATUS    = 'TWITCH_AUTH_STATUS'
export const TWITCH_AUTH_REQUEST   = 'TWITCH_AUTH_REQUEST'
export const TWITCH_AUTH_REQUESTED = 'TWITCH_AUTH_REQUESTED'
export const TWITCH_AUTH_REFRESH   = 'TWITCH_AUTH_REFRESH'
export const TWITCH_AUTH_SUCCESS   = 'TWITCH_AUTH_SUCCESS'
export const TWITCH_AUTH_FAILURE   = 'TWITCH_AUTH_FAILURE'
export const TWITCH_LOGOUT          = 'TWITCH_LOGOUT'

export const GET_TWITCH_CHANNEL           = 'GET_TWITCH_CHANNEL'
export const RESET_TWITCH_CHANNEL         = 'RESET_TWITCH_CHANNEL'
export const GET_TWITCH_CHANNEL_DETAILS   = 'GET_TWITCH_CHANNEL_DETAILS'
export const RESET_TWITCH_CHANNEL_DETAILS = 'RESET_TWITCH_CHANNEL_DETAILS'

export const GET_TWITCH_FOLLOWING   = 'GET_TWITCH_FOLLOWING'
export const RESET_TWITCH_FOLLOWING = 'RESET_TWITCH_FOLLOWING'
export const GET_TWITCH_FEATURED    = 'GET_TWITCH_FEATURED'
export const RESET_TWITCH_FEATURED  = 'RESET_TWITCH_FEATURED'
export const TWITCH_SEARCH          = 'TWITCH_SEARCH'
export const RESET_TWITCH_SEARCH    = 'RESET_TWITCH_SEARCH'

export const YOUTUBE_LOGIN_STATUS    = 'YOUTUBE_LOGIN_STATUS'
export const YOUTUBE_LOGIN_REQUEST   = 'YOUTUBE_LOGIN_REQUEST'
export const YOUTUBE_LOGIN_REQUESTED = 'YOUTUBE_LOGIN_REQUESTED'
export const YOUTUBE_LOGIN_REFRESH   = 'YOUTUBE_LOGIN_REFRESH'
export const YOUTUBE_AUTH_SUCCESS    = 'YOUTUBE_AUTH_SUCCESS'
export const YOUTUBE_AUTH_FAILURE    = 'YOUTUBE_AUTH_FAILURE'
export const YOUTUBE_LOGOUT          = 'YOUTUBE_LOGOUT'

export const GET_YOUTUBE_CHANNEL           = 'GET_YOUTUBE_CHANNEL'
export const RESET_YOUTUBE_CHANNEL         = 'RESET_YOUTUBE_CHANNEL'
export const GET_YOUTUBE_CHANNEL_DETAILS   = 'GET_YOUTUBE_CHANNEL_DETAILS'
export const RESET_YOUTUBE_CHANNEL_DETAILS = 'RESET_YOUTUBE_CHANNEL_DETAILS'

export const YOUTUBE_SEARCH       = 'YOUTUBE_SEARCH';
export const RESET_YOUTUBE_SEARCH = 'RESET_YOUTUBE_SEARCH';
export const YOUTUBE_POPULAR      = 'YOUTUBE_POPULAR';
export const YOUTUBE_RECENT       = 'YOUTUBE_RECENT';

export const GET_RECENT_CHANNELS_ITEMS = 'GET_RECENT_CHANNELS_ITEMS'
export const SET_RECENT_CHANNELS_ITEM  = 'SET_RECENT_CHANNELS_ITEM'

export const SET_MESSAGE    = 'SET_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';

export const PLAYER_OPEN       = 'PLAYER_OPEN';
export const PLAYER_CLOSE      = 'PLAYER_CLOSE';
export const PLAYER_MINIMIZE   = 'PLAYER_MINIMIZE';
export const PLAYER_REGISTER   = 'PLAYER_REGISTER';
export const PLAYER_DEREGISTER = 'PLAYER_DEREGISTER';
export const PLAYER_PLAY       = 'PLAYER_PLAY';
export const PLAYER_PAUSE      = 'PLAYER_PAUSE';
export const PLAYER_SOURCES    = 'PLAYER_SOURCES';
export const PLAYER_LOADED     = 'PLAYER_LOADED';