export const LOGIN_STATUS   = 'LOGIN_STATUS'
export const LOGIN_REQUEST  = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS  = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE  = 'LOGIN_FAILURE'
export const LOGOUT         = 'LOGOUT'

export const GET_TWITCH_CHANNEL         = 'GET_TWITCH_CHANNEL'
export const GET_TWITCH_CHANNEL_DETAILS = 'GET_TWITCH_CHANNEL_DETAILS'

export const GET_RECENT_CHANNELS_ITEMS = 'GET_RECENT_CHANNELS_ITEMS'
export const SET_RECENT_CHANNELS_ITEM  = 'SET_RECENT_CHANNELS_ITEM'