export const TWITCH_LOGIN_STATUS   = 'TWITCH_LOGIN_STATUS'
export const TWITCH_LOGIN_REQUEST  = 'TWITCH_LOGIN_REQUEST'
export const TWITCH_LOGIN_SUCCESS  = 'TWITCH_LOGIN_SUCCESS'
export const TWITCH_LOGIN_FAILURE  = 'TWITCH_LOGIN_FAILURE'
export const TWITCH_LOGOUT         = 'TWITCH_LOGOUT'

export const GET_TWITCH_CHANNEL           = 'GET_TWITCH_CHANNEL'
export const RESET_TWITCH_CHANNEL         = 'RESET_TWITCH_CHANNEL'
export const GET_TWITCH_CHANNEL_DETAILS   = 'GET_TWITCH_CHANNEL_DETAILS'
export const RESET_TWITCH_CHANNEL_DETAILS = 'RESET_TWITCH_CHANNEL_DETAILS'

export const GET_TWITCH_FOLLOWING   = 'GET_TWITCH_FOLLOWING'
export const RESET_TWITCH_FOLLOWING = 'RESET_TWITCH_FOLLOWING'

export const YOUTUBE_LOGIN_STATUS   = 'YOUTUBE_LOGIN_STATUS'
export const YOUTUBE_LOGIN_REQUEST  = 'YOUTUBE_LOGIN_REQUEST'
export const YOUTUBE_LOGIN_SUCCESS  = 'YOUTUBE_LOGIN_SUCCESS'
export const YOUTUBE_LOGIN_FAILURE  = 'YOUTUBE_LOGIN_FAILURE'
export const YOUTUBE_LOGOUT         = 'YOUTUBE_LOGOUT'

export const GET_YOUTUBE_CHANNEL           = 'GET_YOUTUBE_CHANNEL'
export const RESET_YOUTUBE_CHANNEL         = 'RESET_YOUTUBE_CHANNEL'
export const GET_YOUTUBE_CHANNEL_DETAILS   = 'GET_YOUTUBE_CHANNEL_DETAILS'
export const RESET_YOUTUBE_CHANNEL_DETAILS = 'RESET_YOUTUBE_CHANNEL_DETAILS'

export const GET_RECENT_CHANNELS_ITEMS = 'GET_RECENT_CHANNELS_ITEMS'
export const SET_RECENT_CHANNELS_ITEM  = 'SET_RECENT_CHANNELS_ITEM'

export const SET_MESSAGE    = 'SET_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';